apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext708
  labels:
    app: BoundedContext708
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext708
  template:
    metadata:
      labels:
        app: BoundedContext708
    spec:
      containers:
        - name: BoundedContext708
          image: username/BoundedContext708:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
