server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: 주문
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: BoundedContext708
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: BoundedContext1160
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: BoundedContext672
          uri: http://localhost:8084
          predicates:
            - Path=, /mypages/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: 주문
          uri: http://주문:8080
          predicates:
            - Path=/orders/**, 
        - id: BoundedContext708
          uri: http://boundedContext708:8080
          predicates:
            - Path=, 
        - id: BoundedContext1160
          uri: http://boundedContext1160:8080
          predicates:
            - Path=, 
        - id: BoundedContext672
          uri: http://boundedContext672:8080
          predicates:
            - Path=, /mypages/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
