---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 주문
  labels:
    app: 주문
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 주문
  template:
    metadata:
      labels:
        app: 주문
    spec:
      containers:
        - name: 주문
          image: username/주문:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext708
  labels:
    app: BoundedContext708
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext708
  template:
    metadata:
      labels:
        app: BoundedContext708
    spec:
      containers:
        - name: BoundedContext708
          image: username/BoundedContext708:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext1160
  labels:
    app: BoundedContext1160
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext1160
  template:
    metadata:
      labels:
        app: BoundedContext1160
    spec:
      containers:
        - name: BoundedContext1160
          image: username/BoundedContext1160:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext672
  labels:
    app: BoundedContext672
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext672
  template:
    metadata:
      labels:
        app: BoundedContext672
    spec:
      containers:
        - name: BoundedContext672
          image: username/BoundedContext672:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: 주문
  labels:
    app: 주문
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 주문


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext708
  labels:
    app: BoundedContext708
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext708


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext1160
  labels:
    app: BoundedContext1160
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext1160


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext672
  labels:
    app: BoundedContext672
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext672

